### ISSUE TITLE
Error on Contact Page

### ISSUE THREAD

**Issue by srbarba** [Sebwite/Magento2-SmartSearch#1]
I have a blank page at the contact page.
The error seems to be at default.xml.
You used <layout> tag instead of <page>, and don't forget use <body> tag too for reference Blocks and Containers.

**Comment by srbarba** [comment]
The file should be: 

> `<?xml version="1.0"?>
> <page xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:View/Layout/etc/page_configuration.xsd">
>     <head>
>         <css src="Sebwite_SmartSearch::css/module.css"/>
>     </head>
>     <body>    
>         <referenceContainer name="header-wrapper">
>             <referenceBlock name="top.search">
>                 <arguments>
>                     <argument name="template" xsi:type="string">Sebwite/SmartSeach/templates/form.mini.phtml</argument>
>                 </arguments>
>             </referenceBlock>
>         </referenceContainer>
>     </body>
> </page>`

**Comment by SilvanLaroo** [comment]
I merged your pull request and created a new version, see: https://github.com/Sebwite/Magento2-SmartSearch/releases/tag/1.0.2.
