### ISSUE TITLE
Catalog Search Not wotking

### ISSUE THREAD

**Issue by testtesting058** [Sebwite/Magento2-SmartSearch#3]
Catalog Search Not wotking as per module functionality when i click on search box
![screenshot-localhost 2016-02-09 14-46-43](https://cloud.githubusercontent.com/assets/14326014/12912066/5c9a0d5e-cf3c-11e5-8bbd-8f3af3f23522.png)

like that
![screenshot](https://cloud.githubusercontent.com/assets/14326014/12912087/6dc04044-cf3c-11e5-9e50-417cef37dfc9.png)

**Comment by gammyduck** [comment]
After loading it on a different browser it brought up a broken version of the second picture and that is what replaced it from then on.

**Comment by SilvanLaroo** [comment]
I think this is a cache issue, did you remove cache and static files? Is the css file properly loaded?

**Comment by gammyduck** [comment]
Its a caching issue. I had it initially myself.
