### ISSUE TITLE
PHP 7 & Feature Request

### ISSUE THREAD

**Issue by gammyduck** [Sebwite/Magento2-SmartSearch#4]
Please make smart search PHP 7 compatible.

Also, when I first installed it, it worked even better than intended as it didnt show the pictures or price, only the names.
Is it possible to have a Simple SmartSearch?

**Comment by SilvanLaroo** [comment]
Php 7 is supported in the latest version.

You can create a simple smartsearch integration by extending or overriding the form-mini.js. This file defines the template. If you remove all other values you'll have a simple smartsearch.
