### ISSUE TITLE
Use sebwite magento2-SmartSearch in muy own search bar

### ISSUE THREAD

**Issue by johanDev19** [Sebwite/Magento2-SmartSearch#6]
hello, 

I want to use  magento2-SmartSearch in my own `<form></form>`, not in the magento default `<form></form>` how i can do it?.

my code:
`<form id="Nsearch_mini_form" action="http://159.203.166.138/catalogsearch/result/" method="get">
                <input id="search" type="text" name="q" value="" placeholder="Buscar" class="input-text" maxlength="128" role="combobox" aria-haspopup="false" aria-autocomplete="both" autocomplete="off">
                <button type="submit" title="Search" class="NsubmitSearch Nbutton">
                    <span><i class="fa fa-search" style="font-size: 20px;" aria-hidden="true"></i></span>
                </button>
                <div id="search_autocomplete" class="search-autocomplete" style="display: none;"></div>
            </form>`

I want to use  magento2-SmartSearch in side this code. thanks

**Comment by SilvanLaroo** [comment]
Hi,

You should checkout form-mini.js in the extension, this overrides the default Magento form-mini.js. You should extend this file and provide an extra option: _formSelector_ this defines the form element to be used as search form. If you provide your Nsearch_mini_form as option this search extension will work on your form as expected.

Regards
